### PR TITLE
Fix compiling with strict C99 and C11

### LINKED ISSUE #587: Building in strict C99 mode
Future versions of GCC and Clang will reject implicit function declarations and implicit ints by default. We are trying to get Fedora ready for this change:

* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

To support this, I'm building packages with an instrumented compiler that logs errors in a difficult-to-suppress way, to capture places where these new errors might impact feature probing code.

Running a build, I find these occurrences:

```none
/builddir/build/BUILD/ksh-1.0.4/src/cmd/INIT/w2.c:23: implicit function declaration: iswspace
./Fea8d1662.c:45: implicit function declaration: wcwidth
./Fea8d1662.c:38: implicit function declaration: wcwidth
./Fea8d1796.c:162: defaulting to int
./Fea8d1796.c:161: defaulting to int
./Fea8d6386.c:52: defaulting to int
./Fea8d7175.c:6: defaulting to int
./Fea8d7175.c:6: defaulting to int
./Fea8d7175.c:7: defaulting to int
./Fea8d7175.c:3: defaulting to int
conf.tmp.c:30: implicit function declaration: printf
conf.tmp.c:19: implicit function declaration: open
conf.tmp.c:22: implicit function declaration: strtol
conf.tmp.c:23: implicit function declaration: strtol
conf.tmp.c:20: implicit function declaration: open
./ea8d12739.c:41: implicit function declaration: __xstat
./ea8d12739.c:62: implicit function declaration: getfsstat
./ea8d18213.c:44: implicit function declaration: utimets
./ea8d19014.c:40: implicit function declaration: _open
./ea8d19014.c:84: implicit function declaration: _pathconf
./ea8d19014.c:76: implicit function declaration: _link
./ea8d19014.c:74: implicit function declaration: _getpagesize
./ea8d19014.c:86: implicit function declaration: _rename
./ea8d19014.c:92: implicit function declaration: _truncate
./ea8d19014.c:90: implicit function declaration: _stat
./ea8d19014.c:94: implicit function declaration: _unlink
./ea8d19014.c:96: implicit function declaration: _utime
./ea8d19014.c:70: implicit function declaration: _chmod
./ea8d19014.c:63: implicit function declaration: _chdir
./ea8d19014.c:44: implicit function declaration: _close
./ea8d19014.c:42: implicit function declaration: _fstat
./ea8d19014.c:68: implicit function declaration: _access
./ea8d19014.c:47: implicit function declaration: _read
./ea8d19014.c:61: implicit function declaration: _mkdir
./ea8d19014.c:47: implicit function declaration: _write
./ea8d19014.c:104: implicit function declaration: system
```

These all indicate places where GCC now reports errors at compile time. Many of them were link-time errors before (all the Windows-style `_`-prefixed functions, for example).

But I have a hard time to find the places of the functions that *should* be available, namely:

* `open`
* `printf`
* `strtol`
* `system`

The location of those implicit `int`s also eludes me.

The `__xstat` error is somewhat concerning as well, this function is no longer to be used on current glibc.

The `iswspace` reference I can find due to the full path, but I'm stumped what this is supposed to do. Obviously it's some kind of feature probing, but where is it used?

`wcwidth` is probably harmless, it is correctly detected in the end.

Any help with this is appreciated!

### PR DESCRIPTION
**Pull request by JohnoKing**
This pull request fixes compilation of ksh with strict C99 and strict C11. It has been tested on the following operating systems (amd64):
- Arch Linux (w/ glibc 2.37)
- Void Linux (w/ musl libc 1.1.24)
- FreeBSD 13.2
- DragonFly BSD 6.4
- NetBSD 9.3
- OpenBSD 7.3
- OmniOS CE r151046
- Haiku R1/beta4

Additionally, -std=c11 has been fixed on Cygwin, ~but due to some sort of bug or incompatibility in the Win32 API -std=c99 doesn't compile:~ -std=c99 is now fixed on Cygwin, see latest commit.

The following operating systems have not been tested yet, as I currently don't have access to any of them:
- ~macOS~ Tested by @pghvlaans.
- ~Oracle Solaris~ Tested by @McDutchie.
- ~QNX~ Tested by @McDutchie.
- HP/UX
- AIX
- UnixWare

For testing, I used a cc wrapper that passes all the required compiler flags. Example script:
```sh
#!/bin/sh
# Note: Don't extend the argument list to multiple lines with \
exec cc -std=c99 -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=old-style-definition "$@"
```
The compilers tested consist of many versions of gcc, ranging from GCC 8 up to the current 14.0 git commit. In a similar vein, Clang has been tested on versions ranging from 13.0.0 to the current 17.0 git commit; tcc's latest git commit was also tested.

Changes:
- Removed all old style function definitions and updated them for compatibility with C99 and C23. This is primarily done by changing e.g. `int main()` to `int main(void)`. There were also a few obsolete K&R C constructs that needed modernization.

- Fixed the avalanche of -Wbuiltin-macro-redefined warnings in LLVM 17. Clang 17 (git version) was spamming the terminal with an avalanche of -Wbuiltin-macro-redefined warnings during the build. This was caused by pre-existing hackery that force defined -Os in the C code itself. This is unnecessary and thus the best way to fix the warning avalanche is to remove the macro hackery.

- Fixed mamake compile when using -std=c*. The mamake compile broke because POSIX functionality was disabled by the compiler flag. Code from src/lib/libast/features/standards for enabling feature macros has been reused here to fix the build with -std=c99.

- The build failed in tvsleep.c because of borked header includes. Fixed easily enough by adding an include for ast.h (and updating the requisite mamfile).

- Removed incorrect usage of `_ATFILE_SOURCE`. When compiling on Linux with Clang 17, iffe failed to detect the utimensat function correctly. This was caused by blatantly incorrect usage of `_ATFILE_SOURCE`. If this actually needed to be defined, the correct location for it is in src/lib/libast/features/standards. However, the current macros enable this by default on illumos and glibc 2.10+ via `__EXTENSIONS__` and `_GNU_SOURCE` respectively, making it at best redundant to manually define it, or (in this case) harmful.

- Fixed -std=c99 on NetBSD by avoiding the getfsstat function. The getfsstat function is only provided on NetBSD for binary compatibility and nothing else. As a result, it is not exposed in the headers and using it will cause an implicit function error, killing the build with C99. Iffe detects this function because it does exist on NetBSD, and the comments in mnt.c imply this is intentional. Despite that, using the function on NetBSD via an implicit call is impossible in C99, the function is deprecated, and we don't actually need to use it, so it's best to just avoid getfsstat by undefining the iffe macro for it.

- Fix compiling with -std=c99 on Haiku. On Haiku, the math.h header doesn't have an extern or definition for isnanl, which causes the build to fail with C99. The fpclassify function works just fine, so that's a better choice here than isnanl.

- Removed an unused program from src/lib/libast/misc/recfmt.c that suffered from bitrot.

- Since quite a few operating systems were tested as of this commit, the list of tested operating systems in src/cmd/ksh93/README has been updated to reflect this.

Resolves: https://github.com/ksh93/ksh/issues/587

### CODE REVIEW

**Comment by JohnoKing** [comment]
I managed to fix -std=c99 on Cygwin by redefining `DECLSPEC_NORETURN` to `__attribute__((__noreturn__))`.

**Comment by pghvlaans** [comment]
Tested on a macOS Ventura 13.3 virtual machine (Clang 14.0.3). The regression tests look OK; I just got the same two pty failures I always do (line 1010 and 1011, but I think it might be the VM or something).

File: src/cmd/INIT/mamake.c [hunk 1]
```diff
@@ -93,8 +93,54 @@ static const char usage[] =
...
+/*
+ * For compatibility with compiler flags such as -std=c99, feature macros
+ * must be enabled to prevent the build from failing at the very start.
+ * These are normally handled in src/lib/libast/features/standards; further
+ * information can be found there. Mamake shouldn't need all that much enabled,
+ * so not much is enabled here.
+ */
+
+/* macOS */
+#if (defined(__APPLE__) || defined(__MACH__) || defined(NeXTBSD)) && !defined(_DARWIN_C_SOURCE)
```
Comment (McDutchie) [inline src/cmd/INIT/mamake.c]: On macOS, all three of the macros `__APPLE__` `__MACH__` `NeXTBSD` are defined, so we should use `&&` and not `||` here.

File: src/cmd/INIT/mamake.c [hunk 2]
```diff
@@ -93,8 +93,54 @@ static const char usage[] =
...
+ * (void*)0, being used for function pointers. It warns, or in some cases it even
+ * throws an error. Just use 0 for NULL, as that is always acceptable in C.
+ */
+#if __SUNPRO_C
+#undef  NULL
+#define NULL    0
+#endif /* __SUNPRO_C */
+
+/* Linux */
+#elif defined(__linux__) && !defined(_GNU_SOURCE)
```
Comment (McDutchie) [inline src/cmd/INIT/mamake.c]: _GNU_SOURCE should be defined for Cygwin as well.

File: src/lib/libast/features/fs [hunk 3]
```diff
@@ -179,28 +179,39 @@ cat{
...
+	/*
+	 * NetBSD only provides getfsstat for binary compatibility, and
+	 * does not expose it in the system headers. Using it will
+	 * cause the build to fail with C99 because of an implicit
+	 * function error. We don't actually need this function,
+	 * so it's better to just avoid using it.
+	 */
+	#if defined(__NetBSD__)
+	#undef _lib_getfsstat
+	#endif
```
Comment (McDutchie) [inline src/lib/libast/features/fs]: I'd rather we just define an extern on NetBSD and any other systems where the headers don't expose it. It should work to add the following at the end of features/fs:

```
header sys/param.h
header sys/ucred.h
header sys/mount.h
extern getfsstat int (struct statfs*, int, int)
```

See features/sys and `iffe --man` for comparison and information.

File: src/lib/libast/port/mnt.c [hunk 4]
```diff
@@ -134,8 +134,8 @@ set(Header_t* hp, const char* fs, const char* dir, const char* type, const char*
  * what a crappy interface
  * data returned in static buffer -- ok
  * big chunk of allocated memory that cannot be freed -- come on
- * *and* NetBSD changed the interface somewhere along the line
- * private interface? my bad -- public interface? par for the BSD course
+ * *and* NetBSD changed the interface somewhere along the line to a
+ * private interface? par for the BSD course
```
Comment (McDutchie) [inline src/lib/libast/port/mnt.c]: This edit makes the comment say something completely different; it is criticising NetBSD for changing a public interface. Either leave it as is, or delete lines 134-140 entirely.

File: src/lib/libast/features/fs (hunk 3 above)
Comment (JohnoKing) [reply src/lib/libast/features/fs]: I tested this and it also fixes the build error, but causes nearly every single file compiled to complain with the following warning:
```
In file included from ./ast_fcntl.h:5:0,
                 from /home/johno/ksh/src/lib/libast/include/ast_std.h:68,
                 from /home/johno/ksh/src/lib/libast/include/ast.h:32,
                 from /home/johno/ksh/src/lib/libast/hash/hashlib.h:29,
                 from /home/johno/ksh/src/lib/libast/hash/hashlook.c:26:
./ast_fs.h:13:29: warning: 'struct statfs' declared inside parameter list will not be visible outside of this definition or declaration
 extern int getfsstat(struct statfs*, int, int);
                             ^~~~~~
```

Like getfsstat, `struct statfs` is also not readily exposed by NetBSD's headers, resulting in this warning. I personally would rather avoid fighting against the system headers. It's fairly obvious from how the headers hide this function that getfsstat shouldn't be used on NetBSD.
Granted, the current method used is lacking. Perhaps a test could be added to see if the function actually compiles before defining _lib_getfsstat. The getfsstat_statvfs test already does this, albeit it appears to focus moreso on if getfsstat uses statvfs than anything else.

**Edit:** I've pushed a test fix and it compiles successfully. I'll do a little bit more testing though to make sure it doesn't break anything on e.g. FreeBSD/OpenBSD.

Comment (JohnoKing) [reply src/lib/libast/features/fs]: I've pushed a new getfsstat_statfs feature test and modified the old one to only define _lib_getfsstat if it actually compiles (i.e., _lib_getfsstat is no longer defined just because the function exists). As far as I can tell the compiler error is now gone, and there are no additional compiler warnings either (tested on NetBSD, OpenBSD, DragonFlyBSD and FreeBSD).

Comment (McDutchie) [reply src/lib/libast/features/fs]: Thanks. You're right, that is the best solution.

**Comment by McDutchie** [comment]
Tested successfully on Solaris 11.4 with Solaris Studio cc (-std=c99) and gcc (-std=c11).

Solaris Studio cc gives lots of warnings but it did that before, and many of them are warnings that `UNREACHABLE()` is not reached (go figure).

**Comment by McDutchie** [comment]
Successfully tested on QNX 6.5.0 i386 with gcc 4.4.2, compiled with `-Os -std=c99`.

Only one warning that I think we can ignore:
```
+ cc -Os -std=c99 -DSH_DICT="libshell" -I. -I/home/martijn/src/ksh/JohnoKing-ksh-3ccaf75/src/cmd/ksh93 -Iinclude -I/home/martijn/src/ksh/JohnoKing-ksh-3ccaf75/src/cmd/ksh93/include -I/home/martijn/src/ksh/JohnoKing-ksh-3ccaf75/arch/nto.i386/include/ast -D_API_ast=20100309 -DERROR_CONTEXT_T=Error_context_t -c /home/martijn/src/ksh/JohnoKing-ksh-3ccaf75/src/cmd/ksh93/data/strdata.c
In file included from /home/martijn/src/ksh/JohnoKing-ksh-3ccaf75/src/cmd/ksh93/data/strdata.c:100:
./FEATURE/math: In function 'local_finite':
./FEATURE/math:31: warning: 'finite' is deprecated (declared at /usr/qnx650/target/qnx6/usr/include/math.h:420)
```

Also successfully tested on the same OS with its native `cc`, which does not support any `-std=` flags.
