### PR TITLE
Further robustify .get and .set discipline functions

### LINKED ISSUE #347: PS2 discipline function is prone to crashing
I've been experiencing this crash for a while now, but haven't gotten anywhere debugging it or properly isolating the trigger of it in my kshrc. For some reason my `$PS2` prompt causes ksh to segfault when inputting a command substitution. Reproducer (includes the relevant portion of my kshrc):

```bash
johno $ cat /tmp/kshrc
# Shortened section of kshrc
set -o emacs
euid=$(id -u)

typeset -A color=(
	# RGB colors (useful website: https://rgbcolorcode.com)
	[bright_lavender]=$'\E[38;2;191;148;228m'
	[cornflower_blue]=$'\E[38;2;100;149;237m'
	[cyan_process]=$'\E[38;2;0;183;235m'
	[maya_blue]=$'\E[38;2;102;204;255m'
	[red]=$'\E[38;2;255;0;0m'
	[ultramarine_blue]=$'\E[38;2;51;85;255m'
	[vivid_violet]=$'\E[38;2;170;0;255m'
)

typeset -A format=(
	# Formatting codes
	[bell]=$'\a'
	[reset]=$'\E[0m'
	[start_title]=$'\E]0;'
	[underline]=$'\E[4m'
)

PS1.get()
{
	integer ps1_old_status=$?

	# Reset the $PS2 prompt line number
	(( ps2_lineno=0 ))

	# Set the window title
	print -n "${format[start_title]}$(id -un): $(hostname)-${instance}${format[bell]}"

	# For the root directory, make sure it's shown as one slash.
	# Otherwise, use the directory name
	pwd=$(pwd)
	if [[ $pwd != '/' ]] then
		pwd=${pwd##*/}
	fi

	# Set the $PS1 prompt
	if (( euid == 0 )) then
		.sh.value="${color[vivid_violet]}${pwd}${color[red]} #${format[reset]} "
	else
		.sh.value="${color[ultramarine_blue]}${pwd}${color[cyan_process]} \$${format[reset]} "
	fi

	return $ps1_old_status  # Workaround for #226
}

# TODO: $PS2 causes a crash after typing '$(\n' (occurs more readily with -O2 than -O0)
PS2.get()
{
	integer ps2_old_status=$?

	(( ps2_lineno++ ))
	if (( euid == 0 )) then
		.sh.value=" $(printf "${color[bright_lavender]}${format[underline]}%02d${format[reset]}${color[red]} ⋗${format[reset]} " ${ps2_lineno})"
	else
		.sh.value=" $(printf "${color[maya_blue]}${format[underline]}%02d${format[reset]}${color[cyan_process]} ⋗${format[reset]} " ${ps2_lineno})"
	fi

	return $ps2_old_status  # Workaround for #226
}

# Reproducer for the crash
johno $ ENV=/tmp/kshrc ksh
johno $ foo=$(   # Press enter
Memory fault(coredump)
```

I've also found another reproducer that triggers a crash in a similar manner to #346. Adding `trap -Q` to the start of the `PS2.get` function will intermittently cause this reproducer to crash:
```bash
johno $ ENV=/tmp/kshrc arch/*/bin/ksh
johno $ test \
/home/johno/GitRepos/KornShell/ksh/arch/linux.i386-64/bin/ksh[53]: trap: -Q: unknown option
Usage: trap [-p] [action condition ...]
 Help: trap [ --help | --man ] 2>&1
Memory fault(coredump)
```

### PR DESCRIPTION
**Pull request by McDutchie**
This should fix various crashes that remain, at least:
* when running a PS2 discipline at parse time
* when pressing Ctrl+C on a PS2 prompt
* when a special builtin within a discipline throws an error within a virtual subshell

src/cmd/ksh93/sh/nvdisc.c:
- In both assign() which handles .set disciplines and lookup() which handles .get disciplines, to stop errors in discipline functions from wreaking havoc:
  - Save, reinitialise and restore the lexer state in case the discipline is run at parse time. This happens with PS2; I'm not currently aware of other contexts but that doesn't mean there aren't any or that there won't be any. Plus, I determined by experimenting that doing this here seems to be the only way to make it work reliably. Thankfully the overhead is low.
  - Check the topfd redirection state and run sh_iorestore() if needed. Without this, if a special builtin with a redirection throws an error in a discipline function, its redirection(s) remain permanent. For example, `trap --bad-option 2>/dev/null` in a PS2.get() discipline would kill standard error, including all your prompts.

src/cmd/ksh93/sh/io.c: io_prompt():
- Before getting the value of the PS2 prompt, save the stack state and restore it after. This stops a PS2.get discipline function from corrupting a command substitution that the user is typing. Doing this in assign()/lookup() is ineffective, so do it here.

Fixes: https://github.com/ksh93/ksh/issues/347

### CODE REVIEW

File: src/cmd/ksh93/sh/nvdisc.c [hunk 1]
```diff
@@ -395,11 +411,13 @@ static char*	lookup(Namval_t *np, int type, Sfdouble_t *dp,Namfun_t *handle)
 			nv_setsize(SH_VALNOD,10);
 		}
 		block(bp,type);
-		sh_pushcontext(&sh,&buff,1);
-		jmpval = sigsetjmp(buff.buff,0);
+		sh_pushcontext(&sh, &checkpoint, 1); //SH_JMPCMD);
+		jmpval = sigsetjmp(checkpoint.buff, 0); //1);
```
Comment (McDutchie) [inline src/cmd/ksh93/sh/nvdisc.c]: I still don't understand the difference with the longjmp values. It would be nice to figure this out somehow.

**Review by JohnoKing — APPROVED** [review]
I haven't been able to break this version of the patch at all. It's working just fine with everything I throw at it, including when compiling ksh with different compilers, varying `CCFLAGS` and ASan.

**Comment by McDutchie** [comment]
There is another thing. It's a separate problem, but it's similar, so it would be nice to fix it too.

```
$ PS1="\$(date) \$(echo foo) \$(echo bar) > "
do  9 dec 2021 04:37:10 CET foo bar > echo $(           <-- press Ctrl+D here
> arch/darwin.i386-64/bin/ksh: syntax error: `(' unmatched
Memory fault
```

I think I fixed it; I'll push a commit to this PR.

**Comment by McDutchie** [comment]
Actually, it's worse. That commit fixes it for Ctrl+D, but if you press Ctrl+C instead, it still crashes.

**Comment by McDutchie** [comment]
Okay, for that, sh_fault() needs a similar fix, as sh_syntax() is never reached.

**Comment by McDutchie** [comment]
That fix is going to be slightly more involved than I thought so for clarity's sake it should probably have its own commit. I'll force-push it back out of here. I'll come up with a couple of regression tests and then commit it.
