### PR TITLE
Fix `LINENO` by incrementing it when skipping newlines

### LINKED ISSUE #484: $LINENO incorrect after compound assignment
```sh
record[a]=(
	typeset -a x=(
		[1]=(
			X=1
		)
	)
)
echo "line 8 counted as $LINENO"
```
Output:
```
line 8 counted as 7
```

### PR DESCRIPTION
**Pull request by JohnoKing**
In ksh93u+ 2012-04-23 a while loop was added to `sh_lex()` that skips newlines without incrementing `LINENO`:
https://github.com/ksh93/ksh/blob/4bc8bda11f5dcf2305f53bb46648e2f34269dc20/src/cmd/ksh93/sh/lex.c#L256-L263
2012-04-23 version: https://github.com/ksh93/ksh93-history/blob/2012-04-23/src/cmd/ksh93/sh/lex.c#L338-L345

This oversight has been fixed by incrementing `sh.inlineno` each time a line is skipped.

Resolves: https://github.com/ksh93/ksh/issues/484

### CODE REVIEW

File: src/cmd/ksh93/sh/lex.c [hunk 1]
```diff
@@ -256,7 +256,9 @@ int sh_lex(Lex_t* lp)
 	if(lp->noreserv)
 	{
 		lp->lex.reservok = 0;
-		while((fcgetc(c)) && c==' ' || c== '\t' || c=='\n');
+		while((fcgetc(c)) && c==' ' || c== '\t' || c=='\n')
```
Comment (McDutchie) [inline src/cmd/ksh93/sh/lex.c]: I know this is original code, but is that loop even correct? Should it not be

```c
		while(fcgetc(c) && (c==' ' || c== '\t' || c=='\n'))
```
?

Comment (JohnoKing) [reply src/cmd/ksh93/sh/lex.c]: That loop is indeed wrong (it generated a `-Wparentheses` warning). That problem has been fixed.

Comment (McDutchie) [reply src/cmd/ksh93/sh/lex.c]: Given how fcgetc() is defined, I suppose it's actually equivalent in practical terms. Still, I think that use of parentheses is odd enough to confuse.
