### PR TITLE
slowread(): Turn off O_NONBLOCK for stdin if it is on

### LINKED ISSUE #469: ksh93 doesn't turn off non-blocking mode for stdin if a program it runs leaves it on
Edit:

The non-cumbersome way to reproduce this in Debian Live would be the following:
```
ksh
# the rest is run in ksh

perl -e 'use Fcntl; fcntl(STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) | O_NONBLOCK)'

chfn
# broken

perl -e 'use Fcntl; fcntl(STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK)'

chfn
# works
```

Most shells seem to implicitly turn off non-blocking mode if a program they run leaves it on.
Some of them, like dash, give a useful message while most won't bother.
Maybe there is a reason why ksh93 doesn't turn off non-blocking mode and my googling fails me.

---

Original title: Many interactive programs break in Linux console when ran from ksh93 after "mlterm-fb -e /bin/true"
Original comment:

Programs that break include passwd, chfn, chsh, and many more.
I think this is a bug in ksh93 and not mlterm-fb because I have not been able to reproduce this with other shells.

Commit 2940b3f was the oldest version of ksh93 I tried.

If you would like, you can reproduce this in Debian Live under x86_64 QEMU:
```
curl -LO https://cdimage.debian.org/cdimage/release/11.2.0-live/amd64/iso-hybrid/debian-live-11.2.0-amd64-standard.iso
qemu-system-x86_64 -cpu host -accel kvm -m 1024 -drive file=debian-live-11.2.0-amd64-standard.iso,media=cdrom
```

Run the following in Debian Live:
```
sudo -i

curl -LO https://downloads.sourceforge.net/mlterm/mlterm-3.9.2.tar.gz
tar xf mlterm-3.9.2.tar.gz
cd mlterm-3.9.2
./configure --with-gui=fb
make
make install

curl -L https://codeload.github.com/ksh93/ksh/tar.gz/a833053 -o ksh-a833053.tar.gz
tar xf ksh-a833053.tar.gz
cd ksh-a833053
bin/package make
install -vm 755 arch/linux.i386-64/bin/ksh /usr/local/bin

ksh
# the rest is run in ksh

mlterm-fb -e /bin/true

passwd
# broken

chfn
# broken

chsh
# broken
```

If you try to reproduce this issue using the dash shell, it outputs the following message after mlterm-fb exits:
```
sh: turning off NDELAY mode
```

I think the problem is that mlterm-fb leaves stdin in non-blocking mode and ksh93 is oblivious to it.
Many shells and interactive programs seem to recognize this scenario and do turn off non-blocking mode.
The programs do work again when I turn off non-blocking mode:
```
perl -e 'use Fcntl; fcntl(STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK)'
```

I would be happy to test any suggested patches.

### PR DESCRIPTION
**Pull request by atheik**
This change turns off O_NONBLOCK for stdin if a previously ran
program left it on so that interactive programs that expect it
to be off work properly.

src/cmd/ksh93/sh/io.c: slowread():
- Turn off O_NONBLOCK for stdin if it is on.

Fixes: #469

### CODE REVIEW

File: src/cmd/ksh93/sh/io.c [hunk 1]
```diff
@@ -1969,6 +1969,14 @@ static ssize_t slowread(Sfio_t *iop,void *buff,register size_t size,Sfdisc_t *ha
 		errno = EINTR;
 		return(-1);
 	}
+	fno = sffileno(iop);
```
Comment (McDutchie) [inline src/cmd/ksh93/sh/io.c:1972]: Did you find a case where fno != 0?

Comment (atheik) [reply src/cmd/ksh93/sh/io.c:1972]: I didn't, but later on in the slowread function this isn't hardcoded as 0 either:
https://github.com/ksh93/ksh/blob/af298a350bf233ebf33128fe21771ee065a68083/src/cmd/ksh93/sh/io.c#L1986
Maybe a later commit could change this second sffileno(iop) to reuse fno, or replace both uses with just 0.

By the way, in the piperead function fd isn't reused here:
https://github.com/ksh93/ksh/blob/af298a350bf233ebf33128fe21771ee065a68083/src/cmd/ksh93/sh/io.c#L1919
https://github.com/ksh93/ksh/blob/af298a350bf233ebf33128fe21771ee065a68083/src/cmd/ksh93/sh/io.c#L1930

**Comment by McDutchie** [comment]
OK, looks good to me, I just added a NEWS entry and an update for version.h (the version date) and the COPYRIGHT file. Welcome, I hope to see more of you :)
