### PR TITLE
64-bit transition part 13: the rest of ksh93

### LINKED ISSUE #592: Transition all size variables to `ssize_t`
Reproducer:
```
$ ls -la bigfile
-rw-r--r-- 1 jhj jhj 2751926272 Dec 27 19:25 bigfile
$ BIG="$(cat bigfile)"
$ print -v BIG | wc -c
[1]    647915 segmentation fault (core dumped)  ksh93
```
`bigfile` contains ASCII text; this is ksh93 1.0.4 on a 64-bit Linux system.

### PR DESCRIPTION
**Pull request by JohnoKing**
This is the thirteenth of the thickfold patch series, which enables ksh93 to operate within a 64-bit address space.

This patch applies the rest of the changes to ksh93 necessary for 64-bit memory allocation, along with the usual warning fixes.

Notable changes:
- parse.c: Fixed a build error when using `SHOPT_KIA` (re: 63366e34).
- `sh_pipe()`: Fix broken `SOCK_CLOEXEC` check. The `!SOCK_CLOEXEC` check in the `#if` directive apparently didn't work, as `strace` was showing unnecessary `fcntl` calls were still getting compiled in. Check for `SOCK_CLOEXEC==0` in a non-preprocessor if statement and let the compiler optimize it away, which actually works correctly.
- Also removed some unnecessary `ptrdiff_t` casts.
- Add a (Linux-specific) regression test for allocating 5GB (we check if plenty of RAM is available via /proc/meminfo).
- locale.sh: Disable a test that requires `SHOPT_MULTIBYTE` to work correctly.

Change in the number of warnings on Linux when compiling with clang using `-Wsign-compare -Wshorten-64-to-32 -Wsign-conversion -Wimplicit-int-conversion`: 352 => 37 (progression from part 12 => part 13)

As for the remaining warnings:
- The nvflags warnings that remain will be addressed in a separate follow-up patch of their own (which doesn't affect memory allocation).
- The fix for the remaining warning regarding `iswalpha()` in lex.c is part of https://github.com/ksh93/ksh/pull/942.

Fixes https://github.com/ksh93/ksh/issues/592

### CODE REVIEW

File: src/cmd/ksh93/sh/args.c [hunk 1]
```diff
@@ -477,20 +480,21 @@ struct dolnod *sh_argcreate(char *argv[])
...
 	dp->dolrefcnt=1;	/* use count */
-	dp->dolnum = n;
+	dp->dolnum = (int)n;
 	dp->dolnxt = 0;
 	pp = dp->dolval;
 	sp = (char*)dp + sizeof(struct dolnod) + n*sizeof(char*);
-	while(n--)
+	while(n)
 	{
+		n--;
```
Comment (McDutchie) [inline src/cmd/ksh93/sh/args.c:497]: This looks like an unrelated code style change. Unless I'm missing something, the original `while(n--)` is fine so please leave it.

Comment (McDutchie) [reply src/cmd/ksh93/sh/args.c:497]: Actually, never mind, I see it now. With `n` now an unsigned `size_t`, you're preventing a wraparound if n==0 on entry.

**Comment by McDutchie** [comment]
Can I just take a moment to thank you for all the brilliant work you've been doing lately. This patch series was particularly hard to get right, but you've managed it with no regressions that I can find, and you've submitted it all in a very orderly manner. Hats off! The ability to handle huge values in variables is a major step forward for ksh.

**Comment by McDutchie** [comment]
>  * `sh_pipe()`: Fix broken `SOCK_CLOEXEC` check. The `!SOCK_CLOEXEC` check in the `#if` directive apparently didn't work, as `strace` was showing unnecessary `fcntl` calls were still getting compiled in. Check for `SOCK_CLOEXEC==0` in a non-preprocessor if statement and let the compiler optimize it away, which actually works correctly.

That makes me curious, so I looked up [the definition on Linux](https://codebrowser.dev/glibc/glibc/sysdeps/unix/sysv/linux/bits/socket_type.h.html). What an ugly hack. There's a `__socket_type` enum definition and all its members are also macros that are defined as themselves! I'm surprised the `#if` didn't error out.

We also can't rely on `#ifdef SOCK_CLOEXEC` -- on macOS it's defined, but as 0.

So yeah, looks like your solution is the only right one. It's something to be aware of in future. This might affect other macros on other operating systems, too.

**Comment by McDutchie** [comment]
> We also can't rely on `#ifdef SOCK_CLOEXEC` -- on macOS it's defined, but as 0.

Ah, no it isn't – that's io.c itself that does that.
