### PR TITLE
Shorten command name used to test ENAMETOOLONG exit status

### LINKED ISSUE #331: Build: FreeBSD 13 regression test path.sh errors
I upgraded my development FreeBSD aarch64 box from FreeBSD 12.2 to FreeBSD 13 and found the following regression path.sh test failures. All tests pass on the older FreeBSD.
```
$ arch/*/bin/ksh --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+40201330 2021-11-07
$ bin/shtests
#### Regression-testing /tmp/ksh/arch/freebsd13.arm64-64/bin/ksh ####
...
test path begins at 2021-11-10+09:29:08
	path.sh[886]: Test 7A: exit status or error message for command with long name wrong (expected 127, got 126)
	path.sh[902]: Test 7E: exit status or error message for exec'd command with long name wrong (expected 127, got 126)
test path failed at 2021-11-10+09:29:25 with exit code 2 [ 138 tests 2 errors ]
test path(C.UTF-8) begins at 2021-11-10+09:29:25
	path.sh[886]: Test 7A: exit status or error message for command with long name wrong (expected 127, got 126)
	path.sh[902]: Test 7E: exit status or error message for exec'd command with long name wrong (expected 127, got 126)
test path(C.UTF-8) failed at 2021-11-10+09:29:43 with exit code 2 [ 138 tests 2 errors ]
test path(shcomp) begins at 2021-11-10+09:29:43
	shcomp-path.ksh[926]: Test 7A: exit status or error message for command with long name wrong (expected 127, got 126)
	shcomp-path.ksh[942]: Test 7E: exit status or error message for exec'd command with long name wrong (expected 127, got 126)
```

### PR DESCRIPTION
**Pull request by JohnoKing**
A change in FreeBSD 13 now causes extremely long command names to exit with `errno` set to `E2BIG` if the command name can't fit in the list of arguments. This was causing the regression tests for `ENAMETOOLONG` to fail on FreeBSD 13 because the exit status for these errors differ (`ENAMETOOLONG` uses exit status 127 while `E2BIG` uses exit status 126). To fix the failing regression tests, the command name has been shortened to twice the length of `NAME_MAX`. This length is still long enough to trigger an `ENAMETOOLONG` error without causing an `E2BIG` failure on FreeBSD 13.

Fixes #331

### CODE REVIEW

File: src/cmd/ksh93/tests/path.sh [hunk 1]
```diff
@@ -879,7 +879,8 @@ got=$?
 	"(expected $exp, got $got)"
 
 # Tests for attempting to use a command name that's too long.
-long_cmd=$(awk -v ORS= 'BEGIN { for(i=0;i<500;i++) print "xxxxxxxxxx"; }')
+name_max=$(getconf NAME_MAX $PWD)
```
Comment (McDutchie) [inline src/cmd/ksh93/tests/path.sh]: Some old systems on which ksh works fine don't ship `getconf`. The built-in could be used instead but it may or may not be compiled in, so let's also add a reasonable fallback.
```sh
name_max=$(builtin getconf 2>/dev/null; getconf NAME_MAX . 2>/dev/null || echo 255)
```
(also using `.` instead of `"$PWD"` for brevity's sake; if `$PWD` is used, the expansion needs to be quoted.)
