### PR TITLE
Fix $RANDOM to act consistently in subshells

### LINKED ISSUE #285: $RANDOM does not get re-seeded within a subshell that redirects stdout
The ksh man page says RANDOM variable is supposed to return "a random integer, uniformly distributed between 0 and 32767" each time it's referenced. However, if the value of $RANDOM is used in a subshell that previously redirected the stdout of any command, $RANDOM has the same value if it's read multiple times within the same command. Here's an example of the bizarre behavior.
```
$ ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
$ function rand {
>  print "this redirect should not matter" >/dev/null
>  print $RANDOM
> }
# It returns the same value every time within the loop,
$ for i in {1..3}; do x=$(rand); print $x; done
16720
16720
16720
# but a different value in each loop.
$ for i in {1..3}; do x=$(rand); print $x; done
30698
30698
30698
# When called outside the subshell, each value is different, as expected.
$ for i in {1..3}; do rand; done 
4135
21706
5128
# Without the redirect, it works as intended.
$ function rand_without_redirect { 
> print $RANDOM
}
$ for i in {1..3}; do x=$(rand_without_redirect); print $x; done
4612
23899
10106
```
zsh has a similar behavior that's not quite the same. `man zshparam` says "The values of RANDOM form an intentionally-repeatable pseudo-random sequence; subshells that reference RANDOM will result in identical pseudo-random values unless the value of RANDOM is referenced or seeded in the parent shell in between subshell invocations." But this isn't zsh, and the redirection of a previous command shouldn't matter.

This random number manipulation makes $RANDOM even more cryptographically unsecure than it already was. If anyone was depending on $RANDOM for security - which they shouldn't have been - then they're in for a bad time.

### PR DESCRIPTION
**Pull request by McDutchie**
This fixes the following:
1. Using $RANDOM in a virtual/non-forked subshell no longer
   influences the reproducible $RANDOM sequence in the parent
   environment.
2. When invoking a subshell $RANDOM is now re-seeded (as mksh and
   bash do) so that invocations in repeated subshells (including
   forked subshells) longer produce identical sequences by default.

src/cmd/ksh93/include/variables.h:
- Move 'struct rand' here as it will be needed in subshell.c.
- Add rand_seed member to save pseudorandom generator seed.
- Remove shell pointer.

src/cmd/ksh93/sh/init.c:
- put_rand(): Store given seed in rand_seed while calling srand().
  No longer pointlessly limit the number of possible seeds with the
  RANDMASK bitmask (that mask is to limit the values to 0-32767,
  it should not limit the number of possible sequences to 32768).
- nget_rand(): Instead of using rand(), use rand_r() to update the
  random_seed value. This makes it possible to save/restore the
  current seed of the pseudorandom generator.
- nv_init(): Initialise rand_seed here instead of in sh_main(), as
  this is where the other struct rand members are initialised. Also
  call the initial srand() here. Also, as in put_rand(), do not
  limit the number of seeds (possible sequences) to 32768.

src/cmd/ksh93/sh/main.c: sh_main():
- Remove srand() call that was moved to init.c.

src/cmd/ksh93/sh/subshell.c: sh_subshell():
- Upon entering a virtual subshell, save the current $RANDOM seed
  and state, then reseed $RANDOM for the subshell.
- Upon exiting a virtual subshell, restore $RANDOM seed and state
  and reseed the generator using srand() with the restored seed.

src/cmd/ksh93/tests/variables.sh:
- Add tests for $RANDOM in forked subshells.
- Add test verifying that $RANDOM in a virtual subshell does not
  influence a reproducible $RANDOM sequence in the parent shell.
- Add test for unsetting special variables in a forked subshell.

Co-authored-by: Johnothan King <johnothanking@protonmail.com>
Resolves: https://github.com/ksh93/ksh/issues/285

### CODE REVIEW

File: src/cmd/ksh93/sh/subshell.c [hunk 1]
```diff
@@ -478,6 +480,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 {
 	struct subshell sub_data;
 	register struct subshell *sp = &sub_data;
+	struct rand *rp = (struct rand*)RANDNOD->nvfun;
```
Comment (JohnoKing) [inline src/cmd/ksh93/sh/subshell.c]: I'm getting an intermittent crash when running the variables.sh regression tests:
```
test variables begins at 2021-05-01+19:42:39
shtests: line 375: 2594: Memory fault
test variables failed at 2021-05-01+19:42:40 with exit code 267 [ 171 tests (killed by SIGSEGV) ]
test variables(C.UTF-8) begins at 2021-05-01+19:42:40
test variables(C.UTF-8) passed at 2021-05-01+19:42:40 [ 171 tests 0 errors ]
test variables(shcomp) begins at 2021-05-01+19:42:40
shtests: line 415: 6157: Memory fault
test variables(shcomp) failed at 2021-05-01+19:42:41 with exit code 267 [ 171 tests (killed by SIGSEGV) ]
```

The `RANDNOD->nvfun` pointer can change inside of the subshell, which sometimes causes this crash (since `rp` becomes an alias to the wrong pointer).

Additionally, if the last command in a script is inside of a subshell, `$RANDOM` doesn't get reseeded (since ksh avoids creating a subshell as an optimization). This bug isn't specific to `$RANDOM`, as `${.sh.subshell}` also exhibits a similar bug:
```sh
$ arch/*/bin/ksh -c 'RANDOM=123; (echo $RANDOM)'
32365
$ arch/*/bin/ksh -c 'RANDOM=123; (echo $RANDOM)'
32365
$ arch/*/bin/ksh -c 'RANDOM=123; (echo $RANDOM)'
32365
$ arch/*/bin/ksh -c '(echo ${.sh.subshell})'
0
```

<details open>
<summary>The following patch should fix all of these issues</summary>

```diff
--- a/src/cmd/ksh93/include/variables.h
+++ b/src/cmd/ksh93/include/variables.h
@@ -34,6 +34,7 @@ struct rand
 	unsigned int	rand_seed;
 	int32_t		rand_last;
 };
+unsigned int rand_seed_seq;
 
 /* The following defines must be kept synchronous with shtab_variables[] in data/variables.c */
 
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -111,7 +111,6 @@ static struct subshell
 static char subshell_noscope;	/* for temporarily disabling all virtual subshell scope creation */
 
 static unsigned int subenv;
-static unsigned int rand_seed_seq;
 
 /*
  * This routine will turn the sftmp() file into a real /tmp file or pipe
@@ -480,7 +479,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 {
 	struct subshell sub_data;
 	register struct subshell *sp = &sub_data;
-	struct rand *rp = (struct rand*)RANDNOD->nvfun;
+	struct rand *rp;
 	int jmpval,isig,nsig=0,fatalerror=0,saveerrno=0;
 	unsigned int savecurenv = shp->curenv;
 	int savejobpgid = job.curpgid;
@@ -605,6 +604,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 		shp->cpid = 0;
 		sh_sigreset(0);
 		/* save the current $RANDOM seed and state */
+		rp = (struct rand*)RANDNOD->nvfun;
 		sp->rand_seed = rp->rand_seed;
 		sp->rand_last = rp->rand_last;
 		/* reseed $RANDOM for the subshell */
@@ -867,6 +867,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 		shp->cpipe[1] = sp->cpipe;
 		shp->coutpipe = sp->coutpipe;
 		/* restore $RANDOM seed and state */
+		rp = (struct rand*)RANDNOD->nvfun;
 		rp->rand_seed = sp->rand_seed;
 		rp->rand_last = sp->rand_last;
 		srand(rp->rand_seed);
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1937,8 +1937,10 @@ int sh_exec(register const Shnode_t *t, int flags)
 			flags &= ~OPTIMIZE_FLAG;
 			if(!shp->subshell && !shp->st.trapcom[0] && !shp->st.trap[SH_ERRTRAP] && (flags&sh_state(SH_NOFORK)))
 			{
+				/* This is the last command, so avoid creating a subshell */
 				char *savsig;
 				int nsig,jmpval;
+				struct rand *rp = (struct rand*)RANDNOD->nvfun;
 				struct checkpt *buffp = (struct checkpt*)stkalloc(shp->stk,sizeof(struct checkpt));
 				shp->st.otrapcom = 0;
 				if((nsig=shp->st.trapmax*sizeof(char*))>0 || shp->st.trapcom[0])
@@ -1948,6 +1950,12 @@ int sh_exec(register const Shnode_t *t, int flags)
 					memcpy(savsig,(char*)&shp->st.trapcom[0],nsig);
 					shp->st.otrapcom = (char**)savsig;
 				}
+				/* reseed $RANDOM */
+				rp->rand_seed = shgd->current_pid ^ ++rand_seed_seq;
+				srand(rp->rand_seed);
+				rp->rand_last = -1;
+				/* increment ${.sh.subshell} */
+				shgd->realsubshell++;
 				sh_sigreset(0);
 				sh_pushcontext(shp,buffp,SH_JMPEXIT);
 				jmpval = sigsetjmp(buffp->buff,0);
--- a/src/cmd/ksh93/tests/variables.sh
+++ b/src/cmd/ksh93/tests/variables.sh
@@ -52,6 +52,11 @@ integer rand1=$(
 integer rand2=${ print $RANDOM ;}
 (( rand1 == rand2 )) && err_exit "Test 2: \$RANDOM seed in subshell doesn't change" \
 	"(both results are $rand1)"
+# $RANDOM should be reseeded when the final command is inside of a subshell
+rand1=$($SHELL -c 'RANDOM=1; (echo $RANDOM)')
+rand2=$($SHELL -c 'RANDOM=1; (echo $RANDOM)')
+(( rand1 == rand2 )) && err_exit "Test 3: \$RANDOM seed in subshell doesn't change" \
+	"(both results are $rand1)"
 # Virtual subshells should not influence the parent shell's RANDOM sequence
 RANDOM=456
 exp="$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM"
@@ -736,6 +741,12 @@ actual=$(
 expect=$'4\n3\n3\n2\n1'
 [[ $actual == "$expect" ]] || err_exit "\${.sh.subshell} failure (expected $(printf %q "$expect"), got $(printf %q "$actual"))"
 
+# ${.sh.subshell} should increment when the final command is inside of a subshell
+exp=1
+got=$($SHELL -c '(echo ${.sh.subshell})')
+[[ $exp == $got ]] || err_exit '${.sh.subshell} fails to increment when the final command is inside of a subshell' \
+	"(expected '$exp', got '$got')"
+
 unset IFS
 if	((SHOPT_BRACEPAT)) && command set -o braceexpand
 then	set -- {1..32768}
```

</details>

**Review by JohnoKing — CHANGES_REQUESTED** [review]
See comment

File: src/cmd/ksh93/sh/subshell.c (hunk 1 above)
Comment (McDutchie) [reply src/cmd/ksh93/sh/subshell.c]: I found another case where `RANDOM` needs to be reseeded:  https://github.com/ksh93/ksh/blob/1aec9b06dd0de6c6796702cd128fd796ec7b1c09/src/cmd/ksh93/sh/xec.c#L1963-L1978

Following script outputs five identical values:
```sh
( echo $RANDOM & )
( echo $RANDOM & )
( echo $RANDOM & )
( echo $RANDOM & )
( echo $RANDOM & )
:
```

I'll add a fix to your patch.

Comment (McDutchie) [reply src/cmd/ksh93/sh/subshell.c]: Yikes, I just found a whopper of a bug when triggering that optimisation within a virtual subshell:
```
$ ksh -c '( ( : & ) ); echo this gets run twice'
this gets run twice
this gets run twice
```
This is in 93u+ and ksh2020, too. Simple enough to work around with a `!shp->subshell` check.

File: src/cmd/ksh93/include/variables.h [hunk 2]
```diff
@@ -25,6 +25,15 @@
 #include        <option.h>
 #include        "FEATURE/options"
 #include        "FEATURE/dynamic"
+#include	<nval.h>
```
Comment (JohnoKing) [inline src/cmd/ksh93/include/variables.h:28]: This is a minor nit but shouldn't the Mamfile be updated to handle this `#include <nval.h>`?

<details open>
<summary>Mamfile patch</summary>

```diff
--- a/src/cmd/ksh93/Mamfile
+++ b/src/cmd/ksh93/Mamfile
@@ -311,6 +311,7 @@ make install
 						prev FEATURE/dynamic implicit
 						prev FEATURE/options implicit
 						prev ${PACKAGE_ast_INCLUDE}/option.h implicit
+						prev ${PACKAGE_ast_INCLUDE}/nval.h implicit
 					done include/variables.h
 					prev ${PACKAGE_ast_INCLUDE}/error.h implicit
 					prev ${PACKAGE_ast_INCLUDE}/stak.h implicit
```

</details>

**Review by hyenias — COMMENTED** [review]
I tested this by hand and it seems to work. I am glad you kept the random mask intact for output. I see what you did with seeding using pids. Even though pids may only differ just a few numbers apart and can be reused or easily acquired. I would prefer using fractional seconds from SECONDS to seed in lieu of using /dev/urandom instead of current pid. But I can understand that perhaps using urandom or subsecond time is more of a burden than the call out to getpid().

File: src/cmd/ksh93/include/variables.h (hunk 2 above)
Comment (McDutchie) [reply src/cmd/ksh93/include/variables.h:28]: Yes, good point, I forgot about that. But note there are two versions of nval.h. In this case it would depend on the nval.h in the ksh93 tree (`include/nval.h`), not the libast one.

**Review by JohnoKing — APPROVED** [review]

**Comment by McDutchie** [comment]
>  I would prefer using fractional seconds from SECONDS to seed in lieu of using /dev/urandom instead of current pid.

I've pushed a commit that makes that happen. It adds a new `sh_reseed_rand()` function to init.c that uses some of the macros defined for the `$SECONDS` discipline functions a bit further up the file. The initial seed should now be of much higher quality as it adds a time granularity of 1/10000 second into the mix.

**Comment by hyenias** [comment]
Very nice. Thank you for taking the additional step and improving the quality of the seeding value.
